import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';

export const metadata: Metadata = {
  title: 'Chatbot App',
  description: 'Generated by create next app',
};

const jost = localFont({
  src: [
    {
      path: '../public/fonts/Jost.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../public/fonts/Jost-SemiBold.woff2',
      weight: '600',
      style: 'normal',
    },
    {
      path: '../public/fonts/Jost-Italic.woff2',
      weight: '400',
      style: 'italic',
    },
  ],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={jost.className}>
      <body>{children}</body>
    </html>
  );
}
